import React,{useEffect,useMemo,useState} from 'react';

const api=async(url,opts={})=>{const r=await fetch(url,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;};
const readFile=f=>new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsText(f);});

export default function App(){
  const [health,setHealth]=useState(null),[file,setFile]=useState(null),[priorityFile,setPriorityFile]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ws,setWs]=useState(null),[view,setView]=useState('overview'),[detail,setDetail]=useState(null),[context,setContext]=useState({trend_id:null,event_id:null,record_id:null}),[conversationId,setConversationId]=useState(null),[chat,setChat]=useState([]),[question,setQuestion]=useState('');
  useEffect(()=>{api('/api/health').then(setHealth).catch(()=>setHealth({ok:false}));},[]);
  const currentTrend=useMemo(()=>context.trend_id?ws?.trends?.find(t=>t.trend_id===context.trend_id):null,[context,ws]);
  async function analyze(){if(!file)return;setBusy(true);setErr('');try{const text=await readFile(file);let priority_snapshot=null;if(priorityFile)priority_snapshot=JSON.parse(await readFile(priorityFile));const data=await api('/api/analyze',{method:'POST',body:JSON.stringify({filename:file.name,text,priority_snapshot})});setWs(data);setView('overview');setDetail(null);setContext({trend_id:null,event_id:null,record_id:null});setChat([]);}catch(e){setErr(e.message);}finally{setBusy(false);}}
  async function applyPriority(){if(!priorityFile||!ws)return;setBusy(true);setErr('');try{const snap=JSON.parse(await readFile(priorityFile));const data=await api(`/api/datasets/${ws.dataset_id}/prioritization`,{method:'POST',body:JSON.stringify(snap)});setWs(data);}catch(e){setErr(e.message);}finally{setBusy(false);}}
  async function openEntity(kind,id){setBusy(true);setErr('');try{const d=await api(`/api/datasets/${ws.dataset_id}/${kind}/${id}`);setDetail({kind,...d});setView('detail');if(kind==='trend')setContext({trend_id:id,event_id:null,record_id:null});if(kind==='event')setContext(c=>({...c,event_id:id,record_id:null}));if(kind==='record')setContext(c=>({...c,record_id:id}));}catch(e){setErr(e.message);}finally{setBusy(false);}}
  async function ask(q=question){const text=String(q||'').trim();if(!text||!ws)return;setQuestion('');setChat(c=>[...c,{role:'user',text}]);try{const data=await api('/api/ask',{method:'POST',body:JSON.stringify({conversation_id:conversationId,message:text,context:{dataset_id:ws.dataset_id,...context}})});setConversationId(data.conversation_id);setChat(c=>[...c,{role:'assistant',...data}]);setContext({trend_id:data.resolved_context?.trend_id||context.trend_id,event_id:data.resolved_context?.event_id||context.event_id,record_id:data.resolved_context?.record_id||context.record_id});}catch(e){setChat(c=>[...c,{role:'assistant',text:`Ask Radar failed: ${e.message}`,error:true}]);}}
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="radar-dot"/><div><b>NEXT RADAR</b><span>Dove Intelligence</span></div></div>
      <nav><button className={view==='overview'?'active':''} onClick={()=>setView('overview')} disabled={!ws}>Overview</button><button className={view==='trends'?'active':''} onClick={()=>setView('trends')} disabled={!ws}>Intelligence</button><button className={view==='ask'?'active':''} onClick={()=>setView('ask')} disabled={!ws}>Ask Radar</button></nav>
      <div className="sidebar-foot"><span className={health?.gemini_configured?'ok':'warn'}>{health?.gemini_configured?'Gemini connected':'Gemini key unavailable'}</span><span className={health?.dove_similarity_threshold_configured?'ok':'warn'}>{health?.dove_similarity_threshold_configured?'Dove threshold connected':'BRS threshold fail-closed'}</span><span className="muted">Final choice A · no inferred priority</span></div>
    </aside>
    <main>
      <header><div><div className="eyebrow">PROJECT NEXT / RADAR</div><h1>{ws?'Dove intelligence workspace':'Upload Dove vendor intelligence'}</h1></div>{ws&&<div className="dataset-chip">{ws.dataset_id}</div>}</header>
      {err&&<div className="error-banner">{err}</div>}
      {!ws?<UploadPanel file={file} setFile={setFile} priorityFile={priorityFile} setPriorityFile={setPriorityFile} busy={busy} analyze={analyze}/>:<>
        {view==='overview'&&<Overview ws={ws} openEntity={openEntity} priorityFile={priorityFile} setPriorityFile={setPriorityFile} applyPriority={applyPriority} busy={busy}/>} 
        {view==='trends'&&<TrendGrid ws={ws} openEntity={openEntity}/>} 
        {view==='detail'&&<Detail detail={detail} openEntity={openEntity} setView={setView}/>} 
        {view==='ask'&&<AskPanel chat={chat} question={question} setQuestion={setQuestion} ask={ask} currentTrend={currentTrend} context={context} openEntity={openEntity}/>} 
      </>}
    </main>
    {busy&&<div className="busy"><div className="spinner"/>Radar is analysing…</div>}
  </div>;
}

function UploadPanel({file,setFile,priorityFile,setPriorityFile,busy,analyze}){return <section className="upload-layout"><div className="hero-panel"><div className="eyebrow">VENDOR DATA → RADAR</div><h2>Compress a large Dove signal package into traceable intelligence.</h2><p>Radar begins after HUL receives brand-shortlisted social/event data from a commercial vendor. Upload CSV or JSON. No scraping is performed.</p><label className="drop"><input type="file" accept=".csv,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/><strong>{file?file.name:'Choose vendor CSV / JSON'}</strong><span>Missing values remain missing. Unmapped fields are preserved.</span></label><button className="primary" disabled={!file||busy} onClick={analyze}>Analyse dataset</button></div><div className="side-card"><h3>Optional authoritative priority</h3><p>Choice A is fail-closed. Without an exact existing priority snapshot, Radar will not rank Trends by BRS, momentum, engagement, evidence strength or Gemini judgment.</p><label className="small-drop"><input type="file" accept=".json" onChange={e=>setPriorityFile(e.target.files?.[0]||null)}/>{priorityFile?priorityFile.name:'Attach priority snapshot JSON'}</label><div className="rule">Matching is infrastructure. Intelligence compression, traceability and investigation are the product.</div></div></section>}
function Overview({ws,openEntity,priorityFile,setPriorityFile,applyPriority,busy}){const o=ws.overview;return <><section className="stats">{Object.entries(ws.stats).map(([k,v])=><div key={k}><span>{label(k)}</span><b>{v}</b></div>)}</section>{o.status!=='AVAILABLE'?<div className="failclosed"><b>Prioritisation unavailable — by design.</b><p>{o.prioritization.reason}</p><div className="inline"><label className="small-drop"><input type="file" accept=".json" onChange={e=>setPriorityFile(e.target.files?.[0]||null)}/>{priorityFile?priorityFile.name:'Attach authoritative snapshot'}</label><button onClick={applyPriority} disabled={!priorityFile||busy}>Apply snapshot</button></div></div>:<section><div className="section-title"><div><div className="eyebrow">EXECUTIVE BRIEF</div><h2>What deserves attention</h2></div></div><div className="cards">{o.executive_brief.map(x=><TrendCard key={x.trend_id} trend={x} onClick={()=>openEntity('trend',x.trend_id)} prioritized/>)}</div></section>}<section><div className="section-title"><div><div className="eyebrow">{o.status==='AVAILABLE'?'FULL INTELLIGENCE':'UNRANKED INTELLIGENCE'}</div><h2>{o.status==='AVAILABLE'?'By authoritative actionability band':'Explore detected Trends without implied order'}</h2></div></div>{o.status==='AVAILABLE'?o.band_sections.map(s=><div className="band-block" key={s.band}><h3>{s.band}</h3><div className="cards">{s.trend_ids.map(id=><TrendCard key={id} trend={ws.trends.find(t=>t.trend_id===id)} onClick={()=>openEntity('trend',id)}/>)}</div></div>):<div className="cards">{ws.trends.map(t=><TrendCard key={t.trend_id} trend={t} onClick={()=>openEntity('trend',t.trend_id)}/>)}</div>}</section></>}
function TrendGrid({ws,openEntity}){return <section><div className="section-title"><div><div className="eyebrow">THEME → TREND → EVENT</div><h2>Detected intelligence</h2></div></div>{ws.themes.map(th=><div className="theme" key={th.theme_id}><div className="theme-head"><div><span>{th.theme_id}</span><h3>{th.title}</h3><p>{th.summary}</p></div><div className="labels">{th.labels.map(x=><em key={x}>{x}</em>)}</div></div><div className="cards">{th.trend_ids.map(id=><TrendCard key={id} trend={ws.trends.find(t=>t.trend_id===id)} onClick={()=>openEntity('trend',id)}/>)}</div></div>)}</section>}
function TrendCard({trend,onClick,prioritized}){if(!trend)return null;const p=trend.priority;return <button className="trend-card" onClick={onClick}><div className="card-top"><span>{trend.trend_id}</span>{p&&<b>{p.band}</b>}</div><h3>{trend.title}</h3><p>{trend.summary}</p><div className="labels">{(trend.labels||[]).slice(0,3).map(x=><em key={x}>{x}</em>)}</div><div className="card-foot">{prioritized&&p?<span>Rank {p.priority_rank}</span>:<span>Open intelligence →</span>}</div></button>}
function Detail({detail,openEntity,setView}){if(!detail)return null;const {kind,entity}=detail;return <section><button className="back" onClick={()=>setView('trends')}>← Back</button><div className="detail-hero"><div className="eyebrow">{kind.toUpperCase()} / {entity[`${kind}_id`]||entity.record_id}</div><h2>{entity.title||entity.event_name||entity.topic||entity.caption||'Evidence record'}</h2><p>{entity.summary||entity.description||entity.post_text||entity.caption}</p></div>{kind==='trend'&&<TrendDetail detail={detail} openEntity={openEntity}/>} {kind==='event'&&<EntityChildren title="Records" ids={entity.record_ids} kind="record" openEntity={openEntity}/>} {kind==='record'&&<RecordDetail detail={detail}/>}</section>}
function TrendDetail({detail,openEntity}){const {entity,analysis,evidence,sources}=detail;return <div className="detail-grid"><div><Panel title="Analysis"><Signal label="Momentum" value={analysis.analysis.momentum}/><Signal label="Engagement" value={analysis.analysis.engagement_strength}/><Signal label="Creator concentration" value={analysis.analysis.creator_concentration}/><Signal label="Evidence consistency" value={analysis.analysis.evidence_consistency}/><Signal label="Cultural interpretation" value={analysis.analysis.cultural_interpretation}/><Signal label="Risk / tension" value={analysis.analysis.risk_tension}/></Panel><EntityChildren title="Events" ids={entity.event_ids} kind="event" openEntity={openEntity}/></div><div><Panel title={`Evidence · ${evidence.summary.evidence_strength}`}><p>{evidence.summary.strength_reason}</p>{evidence.assignments.map(x=><button className={`evidence-row ${x.role.toLowerCase()}`} key={x.evidence_id} onClick={()=>openEntity('record',x.record_id)}><b>{x.role}</b><span>{x.record_id}</span><p>{x.rationale}</p></button>)}</Panel><Panel title="Original sources">{sources.length?sources.map(s=><a key={s} href={s} target="_blank" rel="noreferrer">Open original ↗</a>):<p className="muted">Original source link was not supplied in the vendor dataset.</p>}</Panel></div></div>}
function Signal({label,value}){return <div className="signal"><div><b>{label}</b><span className={value.status==='AVAILABLE'?'ok':'warn'}>{value.status}</span></div><p>{typeof value.value==='string'?value.value:value.reason}</p>{value.value&&typeof value.value==='object'&&<pre>{JSON.stringify(value.value,null,2)}</pre>}</div>}
function EntityChildren({title,ids,kind,openEntity}){return <Panel title={title}><div className="entity-links">{ids.map(id=><button key={id} onClick={()=>openEntity(kind,id)}>{id} →</button>)}</div></Panel>}
function RecordDetail({detail}){const r=detail.entity;const metrics=['views','likes','comments','shares','engagement','reach','impressions'];return <div className="detail-grid"><Panel title="Record"><dl>{Object.entries(r).filter(([k])=>!['vendor_metadata','radar_outputs'].includes(k)).map(([k,v])=><React.Fragment key={k}><dt>{label(k)}</dt><dd>{v===null?'Not supplied':Array.isArray(v)?v.join(', '):String(v)}</dd></React.Fragment>)}</dl></Panel><div><Panel title="Metrics"><dl>{metrics.map(k=><React.Fragment key={k}><dt>{label(k)}</dt><dd>{r[k]===null?'Not supplied':String(r[k])}</dd></React.Fragment>)}</dl></Panel><Panel title="Source">{detail.sources?.length?detail.sources.map(s=><a key={s} href={s} target="_blank" rel="noreferrer">Open original ↗</a>):<p className="muted">Original source link was not supplied in the vendor dataset.</p>}</Panel></div></div>}
function AskPanel({chat,question,setQuestion,ask,currentTrend,context,openEntity}){const prompts=['Why does this matter for Dove?','Show me the evidence.','What contradicts this?','What data are we missing?'];return <section className="ask-wrap"><div className="ask-head"><div><div className="eyebrow">CONVERSATIONAL INVESTIGATION</div><h2>Ask Radar</h2><p>{currentTrend?`Investigating ${currentTrend.trend_id} · ${currentTrend.title}`:'Ask about the active Radar dataset or open a Trend first.'}</p></div><div className="context-chip">{context.record_id||context.event_id||context.trend_id||'DATASET'}</div></div><div className="prompt-row">{prompts.map(p=><button key={p} onClick={()=>ask(p)}>{p}</button>)}</div><div className="chat">{chat.length===0&&<div className="empty-chat">Ask Radar retrieves from structured Radar state before it explains.</div>}{chat.map((m,i)=><div key={i} className={`msg ${m.role} ${m.error?'error':''}`}><b>{m.role==='user'?'You':'Radar'}</b><p>{m.text||m.answer}</p>{m.limitations?.length>0&&<div className="limitations">{m.limitations.map((x,j)=><span key={j}>{x}</span>)}</div>}{m.evidence?.length>0&&<div className="evidence-chips">{m.evidence.slice(0,5).map((e,j)=><button key={j} onClick={()=>e.record_id&&openEntity('record',e.record_id)}>{e.role||'EVIDENCE'} · {e.record_id}</button>)}</div>}{m.sources?.length>0&&<div className="sources">{m.sources.map(s=><a href={s} target="_blank" rel="noreferrer" key={s}>Open original ↗</a>)}</div>}</div>)}</div><div className="composer"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask Radar about this intelligence…"/><button className="primary" onClick={()=>ask()}>Ask</button></div></section>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
const label=s=>String(s).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
