import { buildContentText, clean, cosine, stableId } from './utils.mjs';

export async function candidateCluster(records,{provider,similarityThreshold=0.72,topK=8,minClusterSize=2}){
  if(!provider)throw new Error('Embedding provider required for candidate clustering');
  const usable=records.filter(r=>buildContentText(r)); const skipped=records.filter(r=>!buildContentText(r)).map(r=>r.record_id); if(!usable.length)return {dataset_id:records[0]?.dataset_id||null,algorithm:'MUTUAL_TOPK_COSINE_GRAPH_V1',clusters:[],outlier_record_ids:[],skipped_record_ids:skipped,config:{similarity_threshold:similarityThreshold,top_k:topK,min_cluster_size:minClusterSize}};
  const texts=usable.map(r=>`task: clustering | content: ${buildContentText(r)}`);const vectors=await provider.embed(texts,{purpose:'bottom-up dataset clustering'});if(vectors.length!==usable.length)throw new Error('Embedding count mismatch for candidate clustering');
  const neighbors=usable.map(()=>[]);for(let i=0;i<usable.length;i++){const scored=[];for(let j=0;j<usable.length;j++){if(i===j)continue;const s=cosine(vectors[i],vectors[j]);if(s>=similarityThreshold)scored.push([j,s]);}scored.sort((a,b)=>b[1]-a[1]||usable[a[0]].record_id.localeCompare(usable[b[0]].record_id));neighbors[i]=scored.slice(0,topK).map(x=>x[0]);}
  const adj=usable.map(()=>new Set());for(let i=0;i<usable.length;i++){for(const j of neighbors[i])if(neighbors[j]?.includes(i)){adj[i].add(j);adj[j].add(i);}}
  const comps=[];const seen=new Set();for(let i=0;i<usable.length;i++){if(seen.has(i))continue;const stack=[i],comp=[];seen.add(i);while(stack.length){const x=stack.pop();comp.push(x);for(const y of adj[x])if(!seen.has(y)){seen.add(y);stack.push(y);}}comps.push(comp.sort((a,b)=>usable[a].record_id.localeCompare(usable[b].record_id)));}
  const clusters=[],outliers=[];for(const comp of comps){if(comp.length<minClusterSize){for(const idx of comp)outliers.push(usable[idx].record_id);continue;}const ids=comp.map(i=>usable[i].record_id);const centroid=meanVector(comp.map(i=>vectors[i]));const sims=comp.map(i=>cosine(vectors[i],centroid));const anchorIndex=comp[sims.indexOf(Math.max(...sims))];clusters.push({cluster_id:stableId('CAND',ids.slice().sort()),record_ids:ids,anchor_record_id:usable[anchorIndex].record_id,size:ids.length,cohesion:{mean_centroid_similarity:avg(sims),min_centroid_similarity:Math.min(...sims),max_centroid_similarity:Math.max(...sims)},status:'UNREVIEWED'});}
  clusters.sort((a,b)=>b.size-a.size||a.cluster_id.localeCompare(b.cluster_id));outliers.sort();return {dataset_id:usable[0].dataset_id,algorithm:'MUTUAL_TOPK_COSINE_GRAPH_V1',embedding_model:provider.embeddingModel||'provider',embedding_dimension:vectors[0]?.length||null,config:{similarity_threshold:similarityThreshold,top_k:topK,min_cluster_size:minClusterSize},clusters,outlier_record_ids:outliers,skipped_record_ids:skipped,notes:['Discovery parameters are separate from frozen Dove BRS thresholds.']};
}
function meanVector(vs){const d=vs[0].length,out=new Array(d).fill(0);for(const v of vs)for(let i=0;i<d;i++)out[i]+=Number(v[i]);for(let i=0;i<d;i++)out[i]/=vs.length;return out;}
const avg=xs=>xs.reduce((a,b)=>a+b,0)/(xs.length||1);

export async function reviewClusters(candidateResult,records,{provider}){
  if(!provider)throw new Error('Cluster Analyst provider required');const byId=new Map(records.map(r=>[r.record_id,r]));const request={clusters:candidateResult.clusters.map(c=>({...c,records:c.record_ids.map(id=>publicRecord(byId.get(id)))})),outliers:candidateResult.outlier_record_ids.map(id=>publicRecord(byId.get(id)))};let proposal=await provider.reviewClusters(request);let validation=validateProposal(proposal,candidateResult);if(!validation.ok&&provider.repairClusterReview){proposal=await provider.repairClusterReview({request,proposal,errors:validation.errors});validation=validateProposal(proposal,candidateResult);}if(!validation.ok)throw new Error(`Cluster Analyst invalid: ${validation.errors.join('; ')}`);
  const groups=[],rejected=[];for(const op of proposal.operations){if(op.action==='KEEP'){const c=candidateResult.clusters.find(x=>x.cluster_id===op.cluster_ids[0]);groups.push(makeGroup(c.record_ids,[c.cluster_id],[],op.action,op.rationale));}else if(op.action==='SPLIT'){const c=candidateResult.clusters.find(x=>x.cluster_id===op.cluster_ids[0]);for(const g of op.groups)groups.push(makeGroup(g.record_ids,[c.cluster_id],[],op.action,op.rationale));}else if(op.action==='MERGE'){const cs=op.cluster_ids.map(id=>candidateResult.clusters.find(x=>x.cluster_id===id));groups.push(makeGroup([...new Set(cs.flatMap(c=>c.record_ids))],op.cluster_ids,[],op.action,op.rationale));}else if(op.action==='REJECT'){for(const id of op.cluster_ids){const c=candidateResult.clusters.find(x=>x.cluster_id===id);rejected.push({cluster_id:id,record_ids:c.record_ids,status:'REJECTED_BY_CLUSTER_ANALYST',rationale:op.rationale});}}else if(op.action==='PROMOTE_OUTLIER'){groups.push(makeGroup(op.outlier_record_ids,[],op.outlier_record_ids,op.action,op.rationale));}}
  return {dataset_id:candidateResult.dataset_id,groups,rejected_clusters:rejected,remaining_outlier_record_ids:candidateResult.outlier_record_ids.filter(id=>!groups.some(g=>g.source_outlier_record_ids.includes(id))),skipped_record_ids:candidateResult.skipped_record_ids,status:'VALIDATED'};
}
function publicRecord(r){if(!r)return null;const out={};for(const k of ['record_id','event_name','topic','trend','caption','post_text','transcript','description','hashtags','timestamp','platform','creator','account'])out[k]=r[k];return out;}
function makeGroup(record_ids,cluster_ids,outlier_ids,action,rationale){const ids=[...record_ids].sort();return {group_id:stableId('GROUP',ids),record_ids:ids,source_candidate_cluster_ids:[...cluster_ids],source_outlier_record_ids:[...outlier_ids],analyst_action:action,rationale:String(rationale||''),status:'VALIDATED_CANDIDATE'};}
function validateProposal(p,c){const errors=[];if(!p||!Array.isArray(p.operations)){return {ok:false,errors:['operations must be an array']};}const clusterMap=new Map(c.clusters.map(x=>[x.cluster_id,x]));const clusterUsed=new Set(),outUsed=new Set();for(const [idx,op] of p.operations.entries()){if(!['KEEP','SPLIT','MERGE','REJECT','PROMOTE_OUTLIER'].includes(op.action)){errors.push(`op ${idx} invalid action`);continue;}if(op.action==='PROMOTE_OUTLIER'){const ids=op.outlier_record_ids||[];if(!ids.length)errors.push(`op ${idx} missing outliers`);if(new Set(ids).size!==ids.length)errors.push(`op ${idx} duplicate outlier`);for(const id of ids){if(!c.outlier_record_ids.includes(id))errors.push(`op ${idx} unknown outlier ${id}`);if(outUsed.has(id))errors.push(`outlier ${id} processed twice`);outUsed.add(id);}continue;}const ids=op.cluster_ids||[];if(!ids.length)errors.push(`op ${idx} missing clusters`);for(const id of ids){if(!clusterMap.has(id))errors.push(`op ${idx} unknown cluster ${id}`);if(clusterUsed.has(id))errors.push(`cluster ${id} processed twice`);clusterUsed.add(id);}if(op.action==='KEEP'&&ids.length!==1)errors.push('KEEP requires one cluster');if(op.action==='SPLIT'){if(ids.length!==1)errors.push('SPLIT requires one cluster');const original=clusterMap.get(ids[0])?.record_ids||[];const groups=op.groups||[];const flat=groups.flatMap(g=>g.record_ids||[]);if(new Set(flat).size!==flat.length)errors.push('SPLIT duplicates records');if([...flat].sort().join('|')!==[...original].sort().join('|'))errors.push('SPLIT must conserve membership');}if(op.action==='MERGE'&&ids.length<2)errors.push('MERGE requires >=2 clusters');}
  for(const cl of c.clusters)if(!clusterUsed.has(cl.cluster_id))errors.push(`cluster ${cl.cluster_id} not processed`);return {ok:errors.length===0,errors};}
