import { TAXONOMY } from './constants.mjs';
import { assertUniqueIds, clean, stableId, unique } from './utils.mjs';

export async function buildHierarchy(reviewResult,records,{provider}){
  if(!provider)throw new Error('Hierarchy interpretation provider required');const recordIds=assertUniqueIds(records,'record_id','record_id');const byId=new Map(records.map(r=>[r.record_id,r]));const trends=[],events=[];
  for(const group of reviewResult.groups){const ids=[...group.record_ids];if(!ids.length)throw new Error(`Reviewed group ${group.group_id} has no records`);for(const id of ids)if(!recordIds.has(id))throw new Error(`Reviewed group ${group.group_id} references unknown record ${id}`);let raw=await provider.interpretHierarchyGroup({group:{group_id:group.group_id,record_ids:ids,analyst_action:group.analyst_action,rationale:group.rationale},records:ids.map(id=>safeRecord(byId.get(id)))});let validation=validateTrendInterpretation(raw,ids);if(!validation.ok&&provider.repairHierarchyGroup){raw=await provider.repairHierarchyGroup({input:{group,records:ids.map(id=>safeRecord(byId.get(id)))},proposal:raw,errors:validation.errors});validation=validateTrendInterpretation(raw,ids);}if(!validation.ok)throw new Error(`Hierarchy interpretation invalid for ${group.group_id}: ${validation.errors.join('; ')}`);
    const trendId=stableId('TREND',[reviewResult.dataset_id,...ids.slice().sort()]);const eventIds=[];for(const ev of raw.events){const evIds=[...ev.record_ids].sort();const eventId=stableId('EVENT',[trendId,...evIds]);eventIds.push(eventId);events.push({event_id:eventId,trend_id:trendId,title:String(ev.title).trim(),summary:String(ev.summary||'').trim(),labels:validLabels(ev.labels),record_ids:evIds});}
    trends.push({trend_id:trendId,theme_id:null,title:String(raw.title).trim(),summary:String(raw.summary||'').trim(),labels:validLabels(raw.labels),event_ids:eventIds,record_ids:ids.slice().sort(),source_group_id:group.group_id});
  }
  if(!trends.length)return {dataset_id:reviewResult.dataset_id,themes:[],trends:[],events,model_name:provider.modelName||'provider'};
  let themeProposal=await provider.organizeThemes({trends:trends.map(t=>({trend_id:t.trend_id,title:t.title,summary:t.summary,labels:t.labels,record_ids:t.record_ids}))});let themeValidation=validateThemes(themeProposal,trends);if(!themeValidation.ok&&provider.repairThemes){themeProposal=await provider.repairThemes({trends,proposal:themeProposal,errors:themeValidation.errors});themeValidation=validateThemes(themeProposal,trends);}if(!themeValidation.ok)throw new Error(`Theme organization invalid: ${themeValidation.errors.join('; ')}`);
  const trendMap=new Map(trends.map(t=>[t.trend_id,t]));const themes=[];for(const th of themeProposal.themes){const tids=[...th.trend_ids].sort();const recs=unique(tids.flatMap(id=>trendMap.get(id).record_ids)).sort();const themeId=stableId('THEME',[reviewResult.dataset_id,...tids]);themes.push({theme_id:themeId,title:String(th.title).trim(),summary:String(th.summary||'').trim(),labels:validLabels(th.labels),trend_ids:tids,record_ids:recs});for(const id of tids)trendMap.get(id).theme_id=themeId;}
  validateHierarchy({themes,trends,events},records);return {dataset_id:reviewResult.dataset_id,themes,trends,events,model_name:provider.modelName||'provider',notes:['Theme, Trend and Event IDs are deterministic and not model-authored.']};
}
function safeRecord(r){const out={};for(const k of ['record_id','event_name','topic','trend','caption','post_text','transcript','description','hashtags','timestamp','platform','creator','account'])out[k]=r?.[k];return out;}
function validLabels(labels){const xs=Array.isArray(labels)?unique(labels.map(String)):[];for(const x of xs)if(!TAXONOMY.has(x))throw new Error(`Unknown analytical taxonomy label: ${x}`);return xs.length?xs:['EMERGENT_OTHER'];}
function validateTrendInterpretation(p,groupIds){const errors=[];if(!p||typeof p!=='object'||Array.isArray(p))return {ok:false,errors:['response must be object']};if(!clean(p.title))errors.push('trend title required');if(!Array.isArray(p.events)||!p.events.length)errors.push('events required');try{validLabels(p.labels);}catch(e){errors.push(e.message);}const flat=[];for(const [i,e] of (p.events||[]).entries()){if(!clean(e?.title))errors.push(`event ${i} title required`);if(!Array.isArray(e?.record_ids)||!e.record_ids.length)errors.push(`event ${i} record_ids required`);else flat.push(...e.record_ids);try{validLabels(e?.labels);}catch(err){errors.push(err.message);}}if(new Set(flat).size!==flat.length)errors.push('records duplicated across Events');if([...flat].sort().join('|')!==[...groupIds].sort().join('|'))errors.push('Events must exactly conserve Trend/group records');return {ok:errors.length===0,errors};}
function validateThemes(p,trends){const errors=[];if(!p||!Array.isArray(p.themes)||!p.themes.length)return {ok:false,errors:['themes array required']};const known=new Set(trends.map(t=>t.trend_id)),flat=[];for(const [i,t] of p.themes.entries()){if(!clean(t?.title))errors.push(`theme ${i} title required`);if(!Array.isArray(t?.trend_ids)||!t.trend_ids.length)errors.push(`theme ${i} trend_ids required`);else flat.push(...t.trend_ids);for(const id of t?.trend_ids||[])if(!known.has(id))errors.push(`unknown Trend ${id}`);try{validLabels(t?.labels);}catch(e){errors.push(e.message);}}if(new Set(flat).size!==flat.length)errors.push('Trend assigned to multiple Themes');if([...flat].sort().join('|')!==[...known].sort().join('|'))errors.push('Themes must cover every Trend exactly once');return {ok:errors.length===0,errors};}
export function validateHierarchy(h,records){const recs=assertUniqueIds(records,'record_id');assertUniqueIds(h.trends,'trend_id');assertUniqueIds(h.events,'event_id');assertUniqueIds(h.themes,'theme_id');const tm=new Map(h.themes.map(x=>[x.theme_id,x])),trm=new Map(h.trends.map(x=>[x.trend_id,x])),evm=new Map(h.events.map(x=>[x.event_id,x]));for(const t of h.trends){if(!tm.has(t.theme_id))throw new Error(`Trend ${t.trend_id} missing Theme`);if(!tm.get(t.theme_id).trend_ids.includes(t.trend_id))throw new Error(`Theme backlink missing for ${t.trend_id}`);for(const rid of t.record_ids)if(!recs.has(rid))throw new Error(`Trend ${t.trend_id} unknown record ${rid}`);const flat=t.event_ids.flatMap(id=>{const e=evm.get(id);if(!e)throw new Error(`Unknown Event ${id}`);if(e.trend_id!==t.trend_id)throw new Error(`Event ${id} wrong Trend`);return e.record_ids;});if(new Set(flat).size!==flat.length||[...flat].sort().join('|')!==[...t.record_ids].sort().join('|'))throw new Error(`Event membership mismatch for ${t.trend_id}`);}for(const th of h.themes){const expected=unique(th.trend_ids.flatMap(id=>trm.get(id)?.record_ids||[])).sort();if(expected.join('|')!==[...th.record_ids].sort().join('|'))throw new Error(`Theme ${th.theme_id} membership mismatch`);}return true;}
