import { clean, unique } from './utils.mjs';
import { validateHierarchy } from './hierarchy.mjs';

export function buildOverview({datasetId,hierarchy,trendAnalysis,evidence,records,prioritySnapshot=null}){
  validateOverviewBoundary(datasetId,hierarchy,trendAnalysis,evidence,records);const allTrendIds=hierarchy.trends.map(t=>t.trend_id);
  if(!prioritySnapshot){return {dataset_id:datasetId,overview_version:'RADAR_OVERVIEW_V1',status:'NOT_AVAILABLE',prioritization:{status:'NOT_AVAILABLE',reason:'Authoritative frozen actionability/prioritisation output is not connected. Radar will not substitute BRS, momentum, engagement, evidence strength, or an LLM ranking.',provider_name:'UNAVAILABLE_FROZEN_ACTIONABILITY_ADAPTER',references:[]},executive_brief:[],band_sections:[],all_trend_ids:allTrendIds,unprioritized_trend_ids:allTrendIds,selection_method:'NOT_RUN',notes:['Final choice A: prioritisation is fail-closed until an authoritative snapshot is supplied.','Trend/evidence intelligence remains available but is not used as a ranking substitute.']};}
  const refs=validateSnapshot(prioritySnapshot,datasetId,allTrendIds,hierarchy);const trendMap=new Map(hierarchy.trends.map(t=>[t.trend_id,t])),packMap=new Map(trendAnalysis.trends.map(p=>[p.trend_id,p])),sumMap=new Map(evidence.trend_summaries.map(s=>[s.trend_id,s]));const ordered=[...refs].sort((a,b)=>a.priority_rank-b.priority_rank||a.trend_id.localeCompare(b.trend_id));const executive=ordered.slice(0,Math.min(5,ordered.length)).map(ref=>{const t=trendMap.get(ref.trend_id),p=packMap.get(ref.trend_id),s=sumMap.get(ref.trend_id),assign=evidence.assignments.filter(x=>x.trend_id===ref.trend_id);return {trend_id:t.trend_id,theme_id:t.theme_id,title:t.title,summary:t.summary,labels:t.labels,priority:ref,evidence_strength:s.evidence_strength,evidence_ids:assign.map(x=>x.evidence_id),record_ids:t.record_ids,source_links:unique(assign.map(x=>x.source_url).filter(Boolean)),display_signals:{volume:p.analysis.volume,momentum:p.analysis.momentum}};});const bandOrder=[];const grouped=new Map();for(const r of ordered){if(!grouped.has(r.band)){grouped.set(r.band,[]);bandOrder.push(r.band);}grouped.get(r.band).push(r);}const sections=bandOrder.map(b=>({band:b,trend_ids:grouped.get(b).map(x=>x.trend_id),priority_ranks:grouped.get(b).map(x=>x.priority_rank)}));return {dataset_id:datasetId,overview_version:'RADAR_OVERVIEW_V1',status:'AVAILABLE',prioritization:{status:'AVAILABLE',reason:'Exact existing priority snapshot supplied by the authoritative actionability boundary.',provider_name:'AUTHORITATIVE_PRIORITY_SNAPSHOT',references:ordered},executive_brief:executive,band_sections:sections,all_trend_ids:allTrendIds,unprioritized_trend_ids:[],selection_method:'AUTHORITATIVE_PRIORITY_RANK_ONLY',notes:['No priority ranking was inferred inside Radar Overview.']};
}
function validateOverviewBoundary(datasetId,h,a,e,records){if(h.dataset_id!==datasetId||a.dataset_id!==datasetId||e.dataset_id!==datasetId)throw new Error('Dataset identity mismatch at Overview boundary');validateHierarchy(h,records);const tids=new Set(h.trends.map(t=>t.trend_id));if(new Set(a.trends.map(p=>p.trend_id)).size!==tids.size)throw new Error('Trend Analysis coverage mismatch at Overview');if(new Set(e.trend_summaries.map(s=>s.trend_id)).size!==tids.size)throw new Error('Evidence coverage mismatch at Overview');for(const t of h.trends){const p=a.trends.find(x=>x.trend_id===t.trend_id),s=e.trend_summaries.find(x=>x.trend_id===t.trend_id);if(!p||!s)throw new Error(`Missing downstream state for ${t.trend_id}`);if(p.analysis.evidence_consistency?.value?.evidence_strength!==s.evidence_strength)throw new Error(`Evidence strength mismatch for ${t.trend_id}`);}}
function validateSnapshot(snapshot,datasetId,trendIds,hierarchy){if(!snapshot||typeof snapshot!=='object')throw new Error('Priority snapshot must be JSON object');if(snapshot.dataset_id&&snapshot.dataset_id!==datasetId)throw new Error('Priority snapshot dataset_id mismatch');if(!Array.isArray(snapshot.references))throw new Error('Priority snapshot references must be array');const known=new Set(trendIds),seen=new Set(),ranks=new Set(),refs=[];for(const [i,r] of snapshot.references.entries()){const id=clean(r?.trend_id),band=clean(r?.band),rank=Number(r?.priority_rank);if(!id||!known.has(id))throw new Error(`Priority reference ${i} has unknown Trend`);if(seen.has(id))throw new Error(`Priority Trend duplicated: ${id}`);seen.add(id);if(!band)throw new Error(`Priority ${id} band required`);if(!Number.isInteger(rank)||rank<1)throw new Error(`Priority ${id} rank must be positive integer`);if(ranks.has(rank))throw new Error(`Priority rank duplicated: ${rank}`);ranks.add(rank);if(r.source_event_ids){const t=hierarchy.trends.find(x=>x.trend_id===id);for(const eid of r.source_event_ids)if(!t.event_ids.includes(eid))throw new Error(`Priority ${id} references foreign Event ${eid}`);}if(r.source_record_ids){const t=hierarchy.trends.find(x=>x.trend_id===id);for(const rid of r.source_record_ids)if(!t.record_ids.includes(rid))throw new Error(`Priority ${id} references foreign Record ${rid}`);}refs.push({trend_id:id,band,priority_rank:rank,raw_output:r.raw_output??{},source_event_ids:r.source_event_ids||[],source_record_ids:r.source_record_ids||[]});}
  if(seen.size!==known.size)throw new Error('Authoritative priority snapshot must cover every Trend before Radar shows a ranked Overview');return refs;}
