export class RadarRetrievalService{
  constructor(context){this.context=context;this.themes=index(context.themes,'theme_id');this.trends=index(context.trends,'trend_id');this.events=index(context.events,'event_id');this.records=index(context.records,'record_id');this.evidence=index(context.evidence.assignments,'evidence_id');this.summaries=index(context.evidence.trend_summaries,'trend_id');}
  getDataset(){return structuredClone(this.context.dataset);}getThemes(){return structuredClone(this.context.themes);}getTheme(id){return get(this.themes,id);}getTrend(id){return get(this.trends,id);}getEvent(id){return get(this.events,id);}getRecord(id){return get(this.records,id);}getEvidence(id){return get(this.evidence,id);}getAnalysis(id){if(!(id in this.context.analysis))throw new Error(`Unknown Trend ${id}`);return structuredClone(this.context.analysis[id]);}
  getTrendEvidence(id){if(!this.trends.has(id))throw new Error(`Unknown Trend ${id}`);return {trend_id:id,summary:get(this.summaries,id),assignments:structuredClone(this.context.evidence.assignments.filter(x=>x.trend_id===id))};}
  getScores(id){if(this.records.has(id))return {entity_id:id,entity_type:'RECORD',aggregation:'NONE',matching:structuredClone(this.context.matching.record_outputs[id]),brs:structuredClone(this.context.brs.record_outputs[id]),actionability:structuredClone(this.context.actionability.record_outputs[id])};if(this.trends.has(id))return {entity_id:id,entity_type:'TREND',aggregation:'NO_NEW_AGGREGATION',brs:structuredClone(this.context.brs.trend_passthrough[id]),actionability:structuredClone(this.context.actionability.trend_passthrough[id]),authoritative_priority:structuredClone(this.context.actionability.trend_priority[id]??null)};if(this.events.has(id)){const e=this.events.get(id);return {entity_id:id,entity_type:'EVENT',status:'NOT_DEFINED_AT_EVENT_LEVEL',aggregation:'NONE',record_scores:e.record_ids.map(r=>this.getScores(r))};}if(this.themes.has(id)){const t=this.themes.get(id);return {entity_id:id,entity_type:'THEME',status:'NOT_DEFINED_AT_THEME_LEVEL',aggregation:'NONE',trend_scores:t.trend_ids.map(x=>this.getScores(x))};}throw new Error(`Unknown entity ${id}`);}
  getSourceLinks(id){if(!(id in this.context.source_links))throw new Error(`Unknown entity ${id}`);return [...this.context.source_links[id]];}
  getRelated(id){if(this.trends.has(id)){const t=this.trends.get(id);return {theme:t.theme_id,events:[...t.event_ids],records:[...t.record_ids]};}if(this.events.has(id)){const e=this.events.get(id);return {trend:e.trend_id,records:[...e.record_ids]};}if(this.records.has(id)){const events=[...this.events.values()].filter(e=>e.record_ids.includes(id)).map(e=>e.event_id);const trends=[...this.trends.values()].filter(t=>t.record_ids.includes(id)).map(t=>t.trend_id);return {events,trends};}return {};}
}
function index(rows,key){const m=new Map();for(const r of rows){const id=r?.[key];if(!id||m.has(id))throw new Error(`Invalid/duplicate ${key}`);m.set(id,r);}return m;}function get(m,id){if(!m.has(id))throw new Error(`Unknown entity ${id}`);return structuredClone(m.get(id));}
