import crypto from 'node:crypto';
import { ordinalIndex, clean, unique } from './domain/utils.mjs';

export class AskRadarService{
  constructor(retrieval,provider,{datasetId}){this.r=retrieval;this.provider=provider;this.datasetId=datasetId;this.sessions=new Map();}
  async ask(request){const conversationId=clean(request.conversation_id)||`CONV_${crypto.randomUUID()}`;const session=this.sessions.get(conversationId)||{conversation_id:conversationId,dataset_id:this.datasetId,current_trend_id:null,current_event_id:null,current_record_id:null,previously_referenced_entities:[],last_returned_entities:[]};if(request.context?.dataset_id&&request.context.dataset_id!==this.datasetId)return responseBase(conversationId,'DATASET_MISMATCH','The requested dataset is not the active Radar dataset.',session,[],[],['Active dataset mismatch.']);for(const [k,v] of [['current_trend_id',request.context?.trend_id],['current_event_id',request.context?.event_id],['current_record_id',request.context?.record_id]])if(v)session[k]=v;const question=String(request.message||'').trim();if(!question)return responseBase(conversationId,'INVALID_QUERY','Ask Radar needs a question.',session,[],[],['Empty question.']);const intent=routeIntent(question);const resolved=resolveContext(question,session,this.r);Object.assign(session,resolved);const retrievalResult=this.retrieve(intent,resolved,question,session);if(retrievalResult.direct){const resp=responseBase(conversationId,intent,retrievalResult.direct,session,retrievalResult.evidence||[],retrievalResult.sources||[],retrievalResult.limitations||[]);resp.referenced_entities=retrievalResult.entities||[];resp.suggested_followups=suggestions(intent,resolved);session.last_returned_entities=orderedForFollowup(intent,resp);session.previously_referenced_entities=unique([...session.previously_referenced_entities,...resp.referenced_entities]);this.sessions.set(conversationId,session);return resp;}
    const grounding=validateGrounding(intent,retrievalResult.data);if(!grounding.ok){const resp=responseBase(conversationId,intent,grounding.message,session,retrievalResult.evidence||[],retrievalResult.sources||[],grounding.limitations);resp.referenced_entities=retrievalResult.entities||[];resp.suggested_followups=suggestions(intent,resolved);session.last_returned_entities=orderedForFollowup(intent,resp);this.sessions.set(conversationId,session);return resp;}
    let composed;try{composed=await this.provider.composeAskRadar({question,intent,resolvedContext:resolved,retrieved:retrievalResult.data});}catch(e){return responseBase(conversationId,intent,'Ask Radar could not compose the explanation. The retrieved Radar evidence remains available; retry the question.',session,retrievalResult.evidence||[],retrievalResult.sources||[],[`Model error: ${e.message}`]);}
    const verified=verifyComposer(composed,retrievalResult);const resp={conversation_id:conversationId,answer:verified.answer,resolved_context:contextView(session),intent,evidence:retrievalResult.evidence||[],sources:retrievalResult.sources||[],claims:verified.claims,limitations:unique([...(composed.limitations||[]),...(retrievalResult.limitations||[])]),referenced_entities:unique([...(retrievalResult.entities||[]),...(composed.referenced_entities||[])]).filter(id=>entityExists(this.r,id)),suggested_followups:(composed.suggested_followups||[]).slice(0,5)};session.last_returned_entities=orderedForFollowup(intent,resp);session.previously_referenced_entities=unique([...session.previously_referenced_entities,...resp.referenced_entities]);this.sessions.set(conversationId,session);return resp;}
  retrieve(intent,ctx,question,session){const entity=ctx.current_record_id||ctx.current_event_id||ctx.current_trend_id;try{
    if(intent==='SOURCE_LINKS'){if(!entity)return {direct:'Open a Trend, Event, or Record first so I can retrieve its original source.',limitations:['No active entity.']};const sources=this.r.getSourceLinks(entity);return {direct:sources.length?`I found ${sources.length} vendor-supplied original source link${sources.length===1?'':'s'}.`:'Original source link was not supplied in the vendor dataset.',sources,entities:[entity]};}
    if(intent==='BRS_EXPLANATION'){if(!entity)return {direct:'Open a Trend, Event, or Record first so I can retrieve the relevant BRS output.'};const scores=this.r.getScores(entity);return {data:{entity,scores},entities:[entity]};}
    if(intent==='ACTIONABILITY_EXPLANATION'){if(!entity)return {direct:'Open a Trend, Event, or Record first so I can retrieve its existing actionability output.'};const scores=this.r.getScores(entity);const priority=entity.startsWith('TREND_')?scores.authoritative_priority:null;const meaningful=hasMeaningfulActionability(scores);if(!meaningful&&!priority)return {direct:'Authoritative actionability/prioritisation is not available for this entity. Radar is operating fail-closed and will not substitute BRS, momentum, engagement, evidence strength, or an LLM ranking.',entities:[entity],limitations:['Existing actionability output is unavailable.']};return {data:{entity,scores},entities:[entity]};}
    if(intent==='EVIDENCE_RETRIEVAL'||intent==='CONTRADICTORY_EVIDENCE'||intent==='EVIDENCE_STRENGTH'){const trendId=ctx.current_trend_id||trendForEntity(this.r,entity);if(!trendId)return {direct:'I could not resolve a Trend for the current context.'};const ev=this.r.getTrendEvidence(trendId);let assigns=ev.assignments;if(intent==='CONTRADICTORY_EVIDENCE')assigns=assigns.filter(x=>x.role==='CONTRADICTING');const records=assigns.map(x=>this.r.getRecord(x.record_id));const evidence=assigns.map((x,i)=>({...x,record:records[i]}));const sources=unique(assigns.map(x=>x.source_url).filter(Boolean));if(intent==='CONTRADICTORY_EVIDENCE'&&!assigns.length)return {direct:'No record in this Trend is currently classified as contradicting evidence.',entities:[trendId],evidence:[],sources:[]};return {data:{trend:this.r.getTrend(trendId),summary:ev.summary,assignments:assigns},entities:[trendId,...assigns.map(x=>x.record_id)],evidence,sources};}
    if(intent==='TREND_ANALYSIS'||intent==='CREATOR_ANALYSIS'||intent==='MISSING_INFORMATION'){const trendId=ctx.current_trend_id||trendForEntity(this.r,entity);if(!trendId)return {direct:'I could not resolve a Trend for the current context.'};const analysis=this.r.getAnalysis(trendId);const trend=this.r.getTrend(trendId);if(intent==='CREATOR_ANALYSIS')return {data:{trend,creator_concentration:analysis.analysis.creator_concentration},entities:[trendId]};if(intent==='MISSING_INFORMATION'){const missing=Object.entries(analysis.analysis).filter(([,v])=>v.status!=='AVAILABLE').map(([k,v])=>({field:k,status:v.status,reason:v.reason}));return {data:{trend,missing},entities:[trendId],limitations:missing.map(x=>`${x.field}: ${x.reason}`)};}return {data:{trend,analysis},entities:[trendId]};}
    if(intent==='RELATED_ENTITIES'){if(!entity)return {direct:'Open an entity first so I can retrieve detected relationships.'};return {data:{entity,related:this.r.getRelated(entity)},entities:[entity,...Object.values(this.r.getRelated(entity)).flat().filter(x=>typeof x==='string')]};}
    if(intent==='COMPARISON'){const ids=extractIds(question).filter(id=>entityExists(this.r,id));if(ids.length<2)return {direct:'Please reference two Radar entity IDs or compare entities already visible in the current investigation.'};const [a,b]=ids.slice(0,2);return {data:{a:{entity:getAny(this.r,a),scores:this.r.getScores(a)},b:{entity:getAny(this.r,b),scores:this.r.getScores(b)}},entities:[a,b]};}
    // relevance / general investigation
    if(!entity){const themes=this.r.getThemes();return {data:{dataset:this.r.getDataset(),themes},entities:themes.slice(0,5).map(x=>x.theme_id)};}
    const obj=getAny(this.r,entity),scores=this.r.getScores(entity),sources=this.r.getSourceLinks(entity);let analysis=null,evidence=[];const trendId=ctx.current_trend_id||trendForEntity(this.r,entity);if(trendId){analysis=this.r.getAnalysis(trendId);evidence=this.r.getTrendEvidence(trendId).assignments;}return {data:{entity:obj,scores,analysis,evidence},entities:unique([entity,...evidence.map(x=>x.record_id)]),sources};
  }catch(e){return {direct:`I could not retrieve that entity from the active Radar dataset.`,limitations:[e.message]};}}
}
function routeIntent(q){const t=q.toLowerCase();if(/source|link|open original|original|open the (first|second|third|fourth|fifth|1st|2nd|3rd|4th|5th)/.test(t))return 'SOURCE_LINKS';if(/brs|brand relevance|relevance score|which dimensions/.test(t))return 'BRS_EXPLANATION';if(/actionab|priority|prioriti|critical|monitor|watch|band/.test(t))return 'ACTIONABILITY_EXPLANATION';if(/contradict|opposite|mixed evidence/.test(t))return 'CONTRADICTORY_EVIDENCE';if(/show.*evidence|which (posts|reels|records)|evidence behind|supporting/.test(t))return 'EVIDENCE_RETRIEVAL';if(/confidence|strong is the evidence|well supported|evidence strength/.test(t))return 'EVIDENCE_STRENGTH';if(/accelerat|momentum|changed over time|engagement increasing|widespread|temporal/.test(t))return 'TREND_ANALYSIS';if(/who is driving|creator|accounts?/.test(t))return 'CREATOR_ANALYSIS';if(/missing|what data|demographic|geograph|why can.?t/.test(t))return 'MISSING_INFORMATION';if(/compare|more important than|stronger than|versus|\bvs\b/.test(t))return 'COMPARISON';if(/related|connect|which events/.test(t))return 'RELATED_ENTITIES';return 'RELEVANCE_IMPORTANCE';}
function resolveContext(question,session,r){const out={current_trend_id:session.current_trend_id,current_event_id:session.current_event_id,current_record_id:session.current_record_id};for(const id of extractIds(question)){if(id.startsWith('TREND_'))out.current_trend_id=id;else if(id.startsWith('EVENT_'))out.current_event_id=id;else if(id.startsWith('REC_'))out.current_record_id=id;}const ord=ordinalIndex(question);if(ord!==null&&session.last_returned_entities[ord]){const id=session.last_returned_entities[ord];if(id.startsWith('TREND_'))out.current_trend_id=id;if(id.startsWith('EVENT_'))out.current_event_id=id;if(id.startsWith('REC_'))out.current_record_id=id;}if(out.current_record_id){const rel=r.getRelated(out.current_record_id);if(rel.trends?.[0])out.current_trend_id=rel.trends[0];if(rel.events?.[0])out.current_event_id=rel.events[0];}else if(out.current_event_id){const rel=r.getRelated(out.current_event_id);if(rel.trend)out.current_trend_id=rel.trend;}return out;}
function extractIds(q){return unique((String(q).match(/\b(?:THEME|TREND|EVENT|EVID|REC)_[A-Z0-9_]+\b/gi)||[]).map(x=>x.toUpperCase()));}
function getAny(r,id){if(id.startsWith('THEME_'))return r.getTheme(id);if(id.startsWith('TREND_'))return r.getTrend(id);if(id.startsWith('EVENT_'))return r.getEvent(id);if(id.startsWith('REC_'))return r.getRecord(id);if(id.startsWith('EVID_'))return r.getEvidence(id);throw new Error(`Unknown entity ${id}`);}
function entityExists(r,id){try{getAny(r,id);return true;}catch{return false;}}
function trendForEntity(r,id){if(!id)return null;if(id.startsWith('TREND_'))return id;if(id.startsWith('EVENT_'))return r.getEvent(id).trend_id;if(id.startsWith('REC_'))return r.getRelated(id).trends?.[0]||null;if(id.startsWith('EVID_'))return r.getEvidence(id).trend_id;return null;}
function hasMeaningfulActionability(scores){const candidates=[];if(scores.actionability)candidates.push(scores.actionability);if(Array.isArray(scores.record_scores))for(const r of scores.record_scores)candidates.push(r.actionability);const walk=x=>{if(!x||typeof x!=='object')return false;const st=String(x.status||'').toUpperCase();if(st.startsWith('NOT_')||['UNAVAILABLE','MISSING'].includes(st))return false;return ['score','value','band','actionability','ops'].some(k=>x[k]!==undefined&&x[k]!==null)||['AVAILABLE','FINAL','PROVISIONAL'].includes(st);};return candidates.some(walk);}
function validateGrounding(intent,data){if(!data)return {ok:false,message:'Radar could not retrieve enough evidence to answer that question.',limitations:['Retrieval returned no grounded state.']};if(intent==='BRS_EXPLANATION'){const s=data.scores;if(s.entity_type==='RECORD'&&!isMeaningfulBRS(s.brs))return {ok:false,message:'The existing BRS output is unavailable for this record. Radar will not invent a BRS explanation.',limitations:['BRS unavailable.']};if(s.entity_type==='TREND'&&s.brs?.status==='NOT_AVAILABLE')return {ok:false,message:'A Trend-level BRS is not defined. Radar can show the actual record-level BRS outputs instead.',limitations:['No Trend-level BRS aggregation exists.']};}return {ok:true};}
function isMeaningfulBRS(x){if(!x||typeof x!=='object')return false;const st=String(x.status||'').toUpperCase();if(st.startsWith('NOT_')||['UNAVAILABLE','MISSING'].includes(st))return false;return x.score!==undefined&&x.score!==null||['FINAL','PROVISIONAL','AVAILABLE'].includes(st);}
function verifyComposer(c,retrieval){if(!c||typeof c.answer!=='string'||!c.answer.trim())throw new Error('Malformed Ask Radar response');const allowed=new Set(retrieval.entities||[]);for(const ev of retrieval.evidence||[]){if(ev.evidence_id)allowed.add(ev.evidence_id);if(ev.record_id)allowed.add(ev.record_id);}const claims=(c.claims||[]).map(x=>({text:String(x.text||''),type:['data_fact','radar_derived_analysis','insufficient_evidence'].includes(String(x.type).toLowerCase())?String(x.type).toLowerCase():'radar_derived_analysis',evidence_refs:(x.evidence_refs||[]).filter(id=>allowed.has(id))}));return {answer:c.answer.trim(),claims};}
function responseBase(id,intent,answer,s,evidence=[],sources=[],limitations=[]){return {conversation_id:id,answer,resolved_context:contextView(s),intent,evidence,sources,claims:[],limitations,referenced_entities:[],suggested_followups:[]};}
function contextView(s){return {dataset_id:s.dataset_id,trend_id:s.current_trend_id,event_id:s.current_event_id,record_id:s.current_record_id};}
function orderedForFollowup(intent,resp){if(['EVIDENCE_RETRIEVAL','CONTRADICTORY_EVIDENCE'].includes(intent)&&Array.isArray(resp.evidence))return resp.evidence.map(x=>x.record_id).filter(Boolean);return resp.referenced_entities||[];}
function suggestions(intent,ctx){const common=['Show me the evidence.','What contradicts this?','What data are we missing?'];if(ctx.current_trend_id)common.unshift('Why does this matter for Dove?');return common.slice(0,4);}
